#!/usr/bin/env fish

cp /etc/nixos/configuration.nix configuration.nix

for file in redshift.conf
   cp {$HOME/,home/}.config/$file
end

for file in .tmux.conf .gitconfig
   cp {$HOME/,home/}$file
end

for folder in i3 i3status kak fish
   rsync -av {$HOME/,home/}.config/$folder/
end


