#!/usr/bin/env fish

pacman -Qqe | grep -v "$(pacman -Qqm)" > pacman.lst

for file in redshift.conf starship.toml
   cp {$HOME/,home/}.config/$file
end

for file in .tmux.conf .gitconfig
   cp {$HOME/,home/}$file
end

for folder in i3 kak fish
   rsync -av {$HOME/,home/}.config/$folder/
end


