theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
# chip = "*-isa-*"

# [[block]]
# block = "music"
# max_width = 21
# marquee = false
# player = "spotify"
# buttons = ["play", "next"]

# [[block]]
# block = "load"
# interval = 1
# format = "{1m} {5m} {15m}"

[[block]]
block = "cpu"
interval = 0.7

[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

# [[block]]
# block = "custom"
# command = ''' alacritty -e ytop '''

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20

# [[block]]
# block = "backlight"

[[block]]
block = "battery"
device = "BAT0"

[[block]]
block = "net"
device = "wlp108s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_up = true
interval = 5
use_bits = false

# [[block]]
# block = "networkmanager"
# on_click = ''' alacritty -e nmtui '''

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block = "toggle"
text = "dual"
command_state = "xrandr | grep 'HDMI-1 connected'"
command_off = "xrandr --output eDP-1 --mode 3840x2160 --scale 0.5x0.5"
command_on = "xrandr --output eDP-1 --mode 3840x2160 --scale 0.5x0.5 --output HDMI-1 --mode 3840x2160 --above eDP-1"
interval = 5

[[block]]
block = "sound"

# [[block]]
# block = "speedtest"
# bytes = true
# interval = 1800

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

#[[block]]
##block = "custom"
##interval = 999999
##command = "echo '\uF011'"
##on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"
